--use jukebox;
--create table `jukebox`.`songs`
--(songId int not null primary key auto_increment ,
--songName varchar(100),
--albumNAme varchar(100),
--genre varchar(100),
--artistName varchar(100),
--songPath varchar(100)
--);
--insert into `jukebox`.`songs`(songName,albumNAme,genre,artistName,songPath)values('leanon','leanon','pop','pitbull','sfdfdgafhfhgsssf');
--INSERT INTO `jukebox`.`songs` (`songName`, `albumNAme`, `genre`, `artistName`, `songPath`) VALUES ( 'assassains', 'johnwick', 'rock', 'tyler bates', 'adffg');
--INSERT INTO `jukebox`.`songs` (`songName`, `albumNAme`, `genre`, `artistName`, `songPath`) VALUES ( 'Rock\'s', 'nauto', 'rock', 'recardo silva', 'ggfdd');

--updating songs
--update `jukebox`.`songs` SET `songName` = 'cookisien', `albumNAme` = 'naruto', `songPath` = 'src/main/resources/songs/Cookiesan_Sombre_Naruto.wav' where (`songId` = '2');
--update `jukebox`.`songs` SET `songName` = 'yashuharu', `songPath` = 'src/main/resources/songs/Yasuharu_Takanashi_Scene_of_a_Disaster.wav' where (`songId` = '3');
--update `jukebox`.`songs` SET `songId` =  `songName` = 'supergerointro', `albumNAme` = 'avengers', `genre` = 'jazz', `artistName` = 'jack piters', `songPath` = 'src/main/resources/songs/superhero-intro-111393.wav' where (`songId` = '7');
--update `jukebox`.`songs` SET `songId` =  `songName` = 'zuchu-fire', `albumNAme` = 'zuchufire', `genre` = 'pop', `artistName` = 'julius', `songPath` = 'src/main/resources/songs/Zuchu-Fire-New-Song-Download-Mp3_SongsZilla.Net_.wav' where (`songId` = '8');
--UPDATE `jukebox`.`songs` SET `songId` =  `artistName` = 'axssa' WHERE (`songId` = '9');
